### ISSUE TITLE
State should be reset when React component unmounts

### ISSUE THREAD

**Issue by danmarshall** [billba/botchat#86]
Seeing an issue where the previous state is recycled after tearing down the component and creating a new one.

**Comment by eanders-MS** [comment]
Hitting this issue in the emulator as well.

**Comment by billba** [comment]
Eric I'm assigning this to you because I think it likely has to do with your global state thingie, which I don't understand at all.

**Comment by eanders-MS** [comment]
Happy to take it, but not certain it has to do with the global thingie. I think the issue may be that destruction of the Chat component doesn't reset the Redux store.

**Comment by billba** [comment]
Right now Chat isn't a component, it's just a function. I suspect we'll need to turn it back into a component and have it be responsible for clearing your global thingie.

**Comment by eanders-MS** [comment]
I wonder if we need a Redux store per Chat component (if it were a component), to support multiple instances of the component.

**Comment by danmarshall** [comment]
> I wonder if we need a Redux store per Chat component (if it were a component), to support multiple instances of the component
Yeah I think this is what we get "for free" if we turn the Redux store into a private member of the component.

**Comment by billba** [comment]
Oh yeah we probably do.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by billba** [comment]
Could be. Check with me before doing anything drastic.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by eanders-MS** [comment]
I'm going to give it a try in my working branch.

**Comment by eanders-MS** [comment]
Ok, I tried this and it works great for the Chat control itself; doesn't complicate things and also gets rid of a dread global. Problems arise with the DebugView. Because it is a peer component of Chat there isn't a clean way to get them to share Chat's Redux store. I was considering taking DebugView out of BotChat anyway, because it turns out to be less useful than what we could build directly in the emulator. In the emulator we participate in all sides of the conversation (chat<->directline<->botframework<->bot) and can therefore log all http requests and responses rather than just showing activity json.

**Comment by eanders-MS** [comment]
I have a PR in the works for this, but even with this change, I had to do an additional thing in my app to get React to create new Chat instances. React caches and reuses components according to a heuristic that works for most use cases, but not in this one. To force a new instance to be created, I had to make sure the `key` prop changed each time:
```
return <BotChat.Chat key={ Math.random() } { ...props } />
```
In addition to that, I needed to implement a `shouldComponentUpdate` to ensure it only recreated the component when it really needed to (otherwise, it would recreate whenever anything in the store changed).

How React "diffs" component states:
https://facebook.github.io/react/docs/reconciliation.html

**Comment by billba** [comment]
I’m a little surprised about the last part. Since the store is an internal part of the Chat, how could it make its parent be recreated?

**Comment by eanders-MS** [comment]
Oh, sorry I wasn't clear! My app has its own Redux store. `shouldComponentUpdate` runs on a component in my app, and determines whether it needs to recreate the Chat component.

**Comment by billba** [comment]
Aha, got it.

**Comment by danmarshall** [comment]
@eanders-MS for the ``` key={ Math.random() }``` there is still a chance of collision (albeit small). Is there a more deterministic approach we can take? Perhaps getting this from props, or deriving it somehow from existing props?

**Comment by eanders-MS** [comment]
`key={ this.reuseKey++ }`, or use a proper guid.

**Comment by billba** [comment]
+1 for this.reuseKey++

**Comment by billba** [comment]
Fixed by Eric's checkin.
